//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveReadCard.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeaveReadCard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--2017/11/27 羿均 --&gt;
        ///&lt;LeaveCardSetting&gt;
        ///  &lt;Paper&gt;
        ///    &lt;TotalRow&gt;12&lt;/TotalRow&gt;
        ///    &lt;TotalColumn&gt;32&lt;/TotalColumn&gt;
        ///  &lt;/Paper&gt;
        ///
        ///  &lt;!--學號--&gt;
        ///  &lt;StudentNumber&gt;
        ///    &lt;!--學號第一碼--&gt;
        ///    &lt;Position Row=&quot;0&quot; Col=&quot;0&quot; Value=&quot;0&quot; /&gt;
        ///    &lt;Position Row=&quot;1&quot; Col=&quot;0&quot; Value=&quot;1&quot; /&gt;
        ///    &lt;Position Row=&quot;2&quot; Col=&quot;0&quot; Value=&quot;2&quot; /&gt;
        ///    &lt;Position Row=&quot;3&quot; Col=&quot;0&quot; Value=&quot;3&quot; /&gt;
        ///    &lt;Position Row=&quot;4&quot; Col=&quot;0&quot; Value=&quot;4&quot; /&gt;
        ///    &lt;Position Row=&quot;5&quot; Col=&quot;0&quot; Value=&quot;5&quot; /&gt;
        ///    &lt;Position Row=&quot;6&quot; Col [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string LeaveCardSetting {
            get {
                return ResourceManager.GetString("LeaveCardSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ReadCard {
            get {
                object obj = ResourceManager.GetObject("ReadCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap sandglass_unlock_64 {
            get {
                object obj = ResourceManager.GetObject("sandglass_unlock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
